### ISSUE TITLE
Cookie works for 1.7 not works for 2.0

### ISSUE THREAD

**Issue by vistaMeow** [patrickkfkan/patreon-dl#35] opened 2024-10-04 19:50 UTC
after updated from 1.7.0 to 2.0.0, the cookie string stop working for me and give me this warning.
```
warn: PostDownloader: Post # is not viewable by current user
```
The same cookie is still working for 1.7.0

Additionally, I get my cookie from my desktop browser and run the CLI on my NAS

**Comment by patrickkfkan** [comment] 2024-10-05 11:04
I couldn't reproduce. Tested with cookies obtained from Firefox running on Linux and Win10 + `patreon-dl` running under Node v20.17 (Linux).

In your case, do the cookies work on the same machine as your desktop browser from where you obtained them?

**Comment by vistaMeow** [comment] 2024-10-06 22:38
I have reproduce the same on difference device(linux) with nodejs 20.9. for same device, if using version Nodejs V22.3.0 download should success, but for version 20.9, the error occurs.

cause nodejs 20.9 is the latest version official support by my NAS. it will hard to replace it in my environment.

**Comment by patrickkfkan** [comment] 2024-10-10 06:14
> I replace the nodeJS environment to V22.9.0 in docker and succeed fix this issue.

Good to know! I did some tests with various Node versions and confirm the issue exists with v20.9.0 and v20.8.1.

Since the issue only appears in selected Node versions, I do not think it is something that can / should be addressed in `patreon-dl`. I am therefore closing it.

@leopoldo94 , I think your problem is different. Most likely, you did not obtain the correct cookie. Make sure you follow the instructions in the [guide](https://github.com/patrickkfkan/patreon-dl/wiki/How-to-obtain-Cookie).

**Closed by patrickkfkan** 2024-10-10 06:14 UTC
