### ISSUE TITLE
Getting this error when I attempt to download

### ISSUE THREAD

**Issue by groundcontroldp** [patrickkfkan/patreon-dl#27] opened 2024-07-04 19:20 UTC
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream' imported from /usr/local/lib/node_modules/patreon-dl/dist/utils/Fetcher.js
    at packageResolve (internal/modules/esm/resolve.js:655:9)
    at moduleResolve (internal/modules/esm/resolve.js:696:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

**Comment by patrickkfkan** [comment] 2024-09-22 13:33
I am unable to reproduce this. Anyway, I have updated the `patreon-dl` to v2.0.0, which uses Fetch API instead of `node-fetch`. This might resolve the issue you're having here -- just make sure your Node.js version is at v18 or higher.

Closing this issue for now. Feel free to re-open if problem persists.

**Closed by patrickkfkan** 2024-09-22 13:33 UTC
